### PR TITLE
HUIM with testdata

### PR DESCRIPTION
**Pull request by rivalq**
I have added the High Utility Itemset Mining Example with its test data.

- [X] Huim

### CODE REVIEW

**Comment by hex-plex** [comment]
Hmmmm why do i feel this is just good CP in rust  
image

**Comment by rivalq** [comment]
> Hmmmm why do i feel this is just good CP in rust image

Good cp ?

**Comment by hex-plex** [comment]
The 

> > Hmmmm why do i feel this is just good CP in rust image
> 
> Good cp ?

The code looks very CP generic makes me believe its trying to optimizing what set of things would maximize  fitness

**Comment by rivalq** [comment]
> The
> 
> > > Hmmmm why do i feel this is just good CP in rust image
> > 
> > 
> > Good cp ?
> 
> The code looks very CP generic makes me believe its trying to optimizing what set of things would maximize fitness

Yeah, because that's our goal

**Comment by hex-plex** [comment]
i see i see nice

**Pull request merged**
